### ISSUE TITLE
Discovery is not finding some ssm-enabled instances

### ISSUE THREAD

**Issue by bortels** [akittana/aws-virtual-bastion#2]
First off - this is pretty cool.

I am testing with a group of 6 instances I have with SSM enabled, that I can get to via SSM using python and boto3 - but for some reason only 2 of the 6 show up non-grey in the "select instances" list. I am frankly not even sure how to troubleshoot this. Any suggestions welcome.

**Comment by akittana** [comment]
Do all 6 instances show in the AWS console under EC2 > Managed Instances (In the Systems Manager Services section)? 

If all instances are listed there, can you check the browser console (under the debugger/developer tools) to see if there are any errors logged there?

**Comment by bortels** [comment]
They do. They also show when I look using the aws cli. No messages in the console. 

A thought - do you do paging when you grab them? I have a couple hundred instances, and notice that when I get the list with the cli, it only gives me a subset of them in a single call. if the list-instances call isn't handling paging, that may be why I am only seeing a subset (everything that came back in the first page of results)

**Comment by akittana** [comment]
I believe you're correct about the paging, i did some testing and that looks to be the issue. I will update the code by the weekend, and update this issue so that you're notified when that's completed.

Thanks for the feedback!

**Comment by akittana** [comment]
I updated the code to include paging for ec2 and ssm commands. Can you test and let me know if you're still having an issue?

**Comment by bortels** [comment]
It works beautifully now. Close this issue, and thanks!

**Comment by akittana** [comment]
Thanks for the update! And for the feedback.
