### ISSUE TITLE
Cannot set property 'ssmEnabled' of undefined

### ISSUE THREAD

**Issue by KlodAyzak** [akittana/aws-virtual-bastion#4]
Hello, 

The bastion looks very promising. 

I have deployed the index.html and the client.min.js on S3 but I am getting the following error: 
Error retrieving instance details
undefined : Cannot set property 'ssmEnabled' of undefined

I have 4 servers deployed in the region and all of them are correctly displayed in ec2>Managed instances. 
My user also have the credential to run ssm command. 

Do I miss something. It looks like the latest version should correct this bug.

I hope you will have some tought about the issue.

Brgds, 

Claude

**Comment by akittana** [comment]
Thanks for the feedback. You're right the latest version was to help address bugs like this.

Can you let me know how many ec2 instances in total do you have in that region? Do you see any other errors (including checking the console logs in the browser)?

When running the following cli commands, do you see all 4 instances listed in both outputs: 
aws ec2 describe-instances
aws ssm describe-instance-information

Finally, do you see the same issue if you use the version hosted at [https://d3lisvyx2y2896.cloudfront.net/](https://d3lisvyx2y2896.cloudfront.net/) ?

Thanks

**Comment by akittana** [comment]
Hi Claude, can you test with the latest version and confirm if you're issue is now resolved?

Thank you

**Comment by KlodAyzak** [comment]
Hi Abdul, 

It works like a charm !

Thank you for the quick fix.
