### ISSUE TITLE
Add Support for STS Tokens

### ISSUE THREAD

**Issue by stefanlohr** [akittana/aws-virtual-bastion#6]
could you add support for STS generated Tokens as well. We do not work with IAM users at all. we work only with federated access and api credentials via sts.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-cli

this would be AWS_SESSION_TOKEN in addition to AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for direct editing or .credentials file.

**Comment by akittana** [comment]
Thanks for the feedback.

I just updated the authentication prompt with an optional session token field as well as being able to load the session token if it was present in the credentials file.

Can you test and let me know if its working for you?

**Comment by stefanlohr** [comment]
its working (crednential file & input fields). thx a lot.
