### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by robertdavis1** [akittana/aws-virtual-bastion#7]
really cool project here! However, when trying to compile from source and run, I get the following error in my browser console:
Uncaught TypeError: Cannot read property 'crypto' of undefined

Any thoughts? I am extremely new to node/webpack/etc so I am having a hard time figuring this one out. Thanks!

**Comment by akittana** [comment]
Thanks for the feedback! I think this is an issue with the crypto_browserify package that's included with the aws sdk, and my understanding is that it's removed in newer versions. I am still doing some research, but for now can you try replacing the following line in the webpack.config.js file:

exclude: /(node_modules\/aws-sdk|node_modules\/amazon-cognito-identity-js)/,

with: 

exclude: /(node_modules\/aws-sdk|node_modules\/amazon-cognito-identity-js|node_modules\/crypto-browserify)/,

Let me know if this works.

**Comment by robertdavis1** [comment]
That fixed it! Thanks!

**Comment by akittana** [comment]
Thanks for the update!
